spring:
  datasource:
    url: jdbc:mysql://localhost:3308/b2b
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      initial-size: 50
      max-idle: 100
      default-query-timeout: 10000
      default-auto-commit: true

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: shoplaptop0718@gmail.com
    password: clarduowjvdwcqsi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE

file:
  upload-dir: static/images

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    doc-expansion: none
